name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: who am i
        run: |
          whoami

      - name: pwd
        run: |
          pwd

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: npm i
        run: npm i

      - name : rsync
        run: |
          rsync -av  --exclude='.git' --exclude='.github' --exclude='.gitignore' . ~/express

      - name : pm2 restart
        run: pm2 restart ~/express/bin/www

